name: Deploy Python Bot

on:
  push:
    branches:
      - main  # Change to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Or any other version you need

    - name: Install dependencies
      run: |
        cd my_bot
        pip install -r requirements.txt

    - name: Run the bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}  # Store your token in GitHub secrets
      run: |
        cd my_bot
        python bot.py
